spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/erp?serverTimezone=Asia/Seoul
    username: miris
    password: miris

  jpa:
    hibernate:
      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 961417860930-2n137ah6b47i07di7gkj9hjrj2obfvcn.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 1123864901769808
            client-secret: 28fbb704cd3fb40aab3599aa0f8f52be
            scope:
              - email
              - public_profile

          naver:
            client-id: hh51psuy4kAQsNLpns_R
            client-secret: o4Ji18D03t
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        # Naver는 OAuth Client의 provider에 등록되어있지 않으므로 직접 등록해주어야 한다.
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token # Token 받는 주소
            user-info-uri: https://openapi.naver.com/v1/nid/me # profile 정보 받는 주소
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버에서 넘겨준다.
